export const initialPosts = [
  {
    id: 1,
    category: "Hackathons",
    title: "Building an AI-powered campus navigation app — looking for a designer",
    body: "We're a team of 3 heading to HackNexus next month. The idea is an accessible campus wayfinder with real-time room availability. Need someone with a good eye for product design.",
    author: "Riya Sharma",
    initials: "RS",
    tone: "lavender",
    department: "Computer Engineering",
    time: "18 min ago",
    upvotes: 24,
    comments: 8,
    tags: ["React Native", "Design", "AI"],
  },
  {
    id: 2,
    category: "Research Teams",
    title: "Undergrad research opportunity: TinyML for sustainable agriculture",
    body: "Prof. Kulkarni's lab is exploring low-power edge models for crop disease detection. No prior research experience needed — just curiosity and 4–5 hours a week.",
    author: "Arjun Mehta",
    initials: "AM",
    tone: "peach",
    department: "Electronics & Telecom",
    time: "1 hour ago",
    upvotes: 17,
    comments: 5,
    tags: ["Research", "Machine Learning"],
  },
  {
    id: 3,
    category: "College Clubs",
    title: "Design Club's first portfolio review night is this Friday ✨",
    body: "Bring a project you're proud of (or one you're stuck on). We'll pair up, share thoughtful feedback, and have chai. All departments welcome!",
    author: "Nisha Patel",
    initials: "NP",
    tone: "mint",
    department: "Information Technology",
    time: "3 hours ago",
    upvotes: 12,
    comments: 11,
    tags: ["Community", "Design"],
  },
  {
    id: 4,
    category: "Department Groups",
    title: "Anyone up for a weekend DSA study circle?",
    body: "Planning a small group for graph problems and dynamic programming. Beginner-friendly, no pressure — just consistent practice and accountability.",
    author: "Dev Malhotra",
    initials: "DM",
    tone: "blue",
    department: "Computer Engineering",
    time: "5 hours ago",
    upvotes: 9,
    comments: 3,
    tags: ["Study group", "DSA"],
  },
];

export const mentors = [
  { id: 1, name: "Aarav Desai", title: "Senior frontend engineer at Razorpay", initials: "AD", tone: "lavender", rating: 4.9, sessions: 32, match: 98, skills: ["React", "TypeScript", "System design"], available: "Today, 6:30 PM", verified: true },
  { id: 2, name: "Priya Nair", title: "ML Researcher · IIT Bombay", initials: "PN", tone: "peach", rating: 5.0, sessions: 21, match: 93, skills: ["Machine learning", "Python", "MLOps"], available: "Tomorrow, 11:00 AM", verified: true },
  { id: 3, name: "Kabir Shah", title: "Product designer at CRED", initials: "KS", tone: "mint", rating: 4.8, sessions: 18, match: 87, skills: ["Product design", "Figma", "Portfolio"], available: "Wed, 4:00 PM", verified: true },
];

export const navItems = [
  { label: "Home", path: "/", icon: "home" },
  { label: "SkillSwap", path: "/skillswap", icon: "users" },
  { label: "Profilify AI", path: "/profilify", icon: "sparkles" },
  { label: "Trust & Safety", path: "/safety", icon: "shield" },
];
